import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/Context/ThemeProvider";
import { ToastContainer } from "react-toastify";
import ChatProvider from "@/Context/ChatProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chat Bot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased dark:bg-[#212121]`}
      >
        <ThemeProvider>
          <ChatProvider>{children}</ChatProvider>
          <ToastContainer />
        </ThemeProvider>
      </body>
    </html>
  );
}
